module.exports = {
  borderRadius: '50%',
  colorBorder: '#02b0ab',
  colorText: '#555',
  fontFamilyPrimary: 'Open Sans, sans-serif',
  fontFamilySecondary: 'Montserrat, sans-serif',
  colorLink: '#02b0ab',
  colorLinkHover: '#02b0ab',
  colorLinkActive: '#02b0ab',
  scrollBarThumb: '#eaeaea',
  scrollBarTrack: '#f9f9f9',
  scrollBarWidth: '10px',
  colorBright: '#fff',
  colorDark: '#000',
  spaceEight: '3px',
  spaceQuarter: '6px',
  spaceThird: '8px',
  spaceHalf: '12px',
  spaceThirds: '18px',
  space: '24px',
  spaceEighted: '32px',
  spaceQuartered: '36px',
  spaceDouble: '48px',
  spaceDoubleEight: '56px',
  spaceDoubleThirds: '64px',
  spaceTriple: '72px',
  spaceQuad: '96px',
};
