module.exports = {
  backgroundPrimary: '#120f0b',
  overlayPrimary:
    'linear-gradient(135deg, rgba(13,13,13,0.5) 0%,rgba(248,248,248,0.5) 100%)',
  borderRadius: '50%',
  colorBorder: '#02b0ab',
  colorText: '#D8D8D8',
  fontPrimary: 'Open Sans, sans-serif',
  fontPrimaryFamily: 'Open Sans',
  fontPrimaryType: 'sans-serif',
  fontPrimaryCuts: '400, 700',
  fontSecondary: 'Montserrat, sans-serif',
  fontSecondaryFamily: 'Montserrat',
  fontSecondaryType: 'sans-serif',
  fontSecondaryCuts: '400, 700, 900',
  colorPrimary: '#02b0ab',
  colorLink: '#02b0ab',
  colorLinkHover: '#02b0ab',
  colorLinkActive: '#02b0ab',
  colorLinkCurrent: 'red',
  scrollBarThumb: '#333',
  scrollBarTrack: '#ccc',
  scrollBarWidth: '2px',
  colorBright: '#fff',
  colorDark: '#000',
  spaceEight: '3px',
  spaceQuarter: '6px',
  spaceThird: '8px',
  spaceHalf: '12px',
  spaceThirds: '18px',
  space: '24px',
  spaceEighted: '32px',
  spaceQuartered: '36px',
  spaceDouble: '48px',
  spaceDoubleEight: '56px',
  spaceDoubleThirds: '64px',
  spaceTriple: '72px',
  spaceQuad: '96px',
  gridSpaceGutter: '56px', // spaceDoubleEight
};
